# Generated by Django 5.0.7 on 2024-07-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Groups',
        ),
        migrations.AlterModelTable(
            name='groups',
            table='group',
        ),
    ]
